### ISSUE TITLE
Parity with the JS version

### ISSUE THREAD

**Issue by mourner** [delfrrr/delaunator-cpp#2]
@delfrrr happy to discover this port — great work! Just wanted to point out that several fixes that were made in the last week are very important for the algorithm robustness, so should definitely be ported out:

- [x] https://github.com/mapbox/delaunator/commit/dcfaf9234e60f6e8d19b47124296bc6b08b7e2f6
- [x] https://github.com/mapbox/delaunator/commit/3a61ecc252c9d9c62027ac61f06315eced849fc0
- [x] https://github.com/mapbox/delaunator/commit/b1f360c45875e4956ab22d3bde1f0d7e8e45f9a5
- [x] https://github.com/mapbox/delaunator/commit/0cea584b4642fa9e6552c2be6045be9a10a640c0
- [x] https://github.com/mapbox/delaunator/commit/77a7992772f98dc42cf7a28735532b709ba772ec
- [x] https://github.com/mapbox/delaunator/commit/d7a7ce61389cb27e4290769f3ab76255fa884e1c

I'd also recommend porting over the tests from the JS version to make sure the edge cases are handled the same way.

**Comment by morishuz** [comment]
this is great! thanks for pointing this out.

we already discovered the hash key issue overrun but came up with a different fix  - essentially something like:

`return Math.floor(pseudoAngle(x - this._cx, y - this._cy) * (this._hashSize-1) `

but also added a guard for division by zero (admittedly not as much of an issue in js) for the case that:

`(Math.abs(dx) + Math.abs(dy)` = 0

**Comment by mourner** [comment]
@morishuz your hash key fix will have a different behavior — essentially the last item in the hash will almost never be used. I'd recommend keeping parity with the JS version. 

As for the division by zero check — it's unnecessary because a point can't be equal to the seed triangles' circumcenter.

**Comment by delfrrr** [comment]
@mourner thanks! It was a bit a surprise to see that issue discovered by @morishuz with hashing was just fixed in JS version along with other improvements.

Yes that's a plan:
 * delaunator-cpp as a port should follow the logic of JS version as close as possible so it's easy to port new changes
* I will add test from JS version (already started)
* Then I will port new changes provided by @mourner

**Comment by mourner** [comment]
Also note that the code changed quite a bit in https://github.com/mapbox/delaunator/pull/32

**Comment by delfrrr** [comment]
Not sure about https://github.com/delfrrr/delaunator-cpp/commit/4f072c24113626ed921d2d7a33b69b12e9e093bf

My test does not show broken triangles even without race condition fix 🤔

**Comment by delfrrr** [comment]
Made it finally very close to `delaunator@3.0.1`; I guess that's it

**Comment by mourner** [comment]
Awesome! There's also this nice optimization that didn't yet make it into release but will: https://github.com/mapbox/delaunator/pull/33
